### PR TITLE
Deployment fixes

### PR DESCRIPTION
**Pull request by lindsayydevine**
This has the fix that the feature component will grow on hover and act like a button itself.

### CODE REVIEW

**Comment by toanquoctran** [comment]
lgtm!

**Comment by NathanG-02** [comment]
Deployment fixes worked on Vercel for the demo, looks good to me

**Review by toanquoctran — APPROVED** [review]
lgtm!

**Review by NathanG-02 — APPROVED** [review]
Deployment fixes worked on Vercel for the demo... looks good to me

**Pull request merged**
