### PR TITLE
Member Stats

### PR DESCRIPTION
**Pull request by toanquoctran**
Member Stats

### CODE REVIEW

**Comment by NathanG-02** [comment]
Page looks good, user list functions as expected, updating the selected user window and the stats graph
All metrics within the selected user window seem to be correctly generated
Graph controls function as expected as well

**Review by NathanG-02 — APPROVED** [review]
Page looks good, user list functions as expected, updating the selected user window and the stats graph
All metrics within the selected user window seem to be correctly generated
Graph controls function as expected as well

**Comment by lindsayydevine** [comment]
It will not allow me to approve this merge request because it says there are merge conflicts that must be resolved.

**Review by lindsayydevine — APPROVED** [review]
The member stats buttons work and properly display information with special info for moderators. The return home button reroutes to the landing page but that should be an easy fix that will also be made to the other return buttons on other pages. Overall good work, the feature is both aesthetically pleasing & has correct working functionality

**Pull request merged**
